### ISSUE TITLE
bug: [NG-ZORRO]: Error: [@ant-design/icons-angular]:the icon appstore-add-o does not exist or is not registered.

### ISSUE THREAD

**Issue by juju4** [acquahsamuel/cleansheet-ai-resume-builder#8]
Tried with latest commit, few fix but interface is up and not reacting on any button/action with following message in cli
```
$ ng serve
[...]
Application bundle generation complete. [9.761 seconds]

Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
Re-optimizing dependencies because lockfile has changed
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
Re-optimizing dependencies because lockfile has changed
[NG-ZORRO]: Error: [@ant-design/icons-angular]:the icon appstore-add-o does not exist or is not registered.
    at IconNotFoundError (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:387:10)
    at _NzIconService.getRenderedContent (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:505:13)
    at eval (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:692:25)
    at new ZoneAwarePromise (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:1385:25)
    at _NzIconDirective._changeIcon (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:685:12)
    at eval (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:1058:35)
    at _ZoneDelegate.invoke (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:369:28)
    at ZoneImpl.run (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:111:43)
    at _NgZone.runOutsideAngular (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-H6F6Z4C2.js:6742:24)
    at _NzIconDirective.changeIcon2 (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:1057:17)
[NG-ZORRO]: Error: [@ant-design/icons-angular]:the icon setting-o does not exist or is not registered.
    at IconNotFoundError (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:387:10)
    at _NzIconService.getRenderedContent (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:505:13)
    at eval (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:692:25)
    at new ZoneAwarePromise (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:1385:25)
    at _NzIconDirective._changeIcon (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:685:12)
    at eval (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:1058:35)
    at _ZoneDelegate.invoke (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:369:28)
    at ZoneImpl.run (/home/user/tmp/cleansheet-resume-builder/node_modules/zone.js/fesm2015/zone-node.js:111:43)
    at _NgZone.runOutsideAngular (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-H6F6Z4C2.js:6742:24)
    at _NzIconDirective.changeIcon2 (/home/user/tmp/cleansheet-resume-builder/.angular/cache/18.2.6/vite/deps_ssr/chunk-EUDLGYKB.js:1057:17)
```

**Comment by juju4** [comment]
I did a new setup and don't get this error anymore but stuck at login page. clicking register does nothing. same with "forgot password"
Outside of node console logging (with nothing), what else is available to debug? any query log?
is there a required version of nodejs? tested with nodejs 23.1.0 as standalone test setup.
In the instructions, there is a "Open package.json", but no follow-up. is there a mandatory editing?

It seems to be the same on public website https://cleansheet-resume.vercel.app/auth/login = currently nothing happening when clicking on register or forgot password

**Comment by acquahsamuel** [comment]
@juju4 i have made updates on the entire project. We are no more using ng-zorro library. We are using ng prime going forward. You can make a fresh pull.
